packages:
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@sentry-internal/node-native-stacktrace'
  - core-js
  - cpu-features
  - esbuild
  - eslint-plugin-n8n-nodes-base
  - msgpackr-extract
  - oracledb
  - protobufjs
  - sharp
  - sqlite3
  - ssh2
  - unrs-resolver
